[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = "MIT"
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
log = "0.4"
dirs = "5.0"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
mlua = { version = "0.9.5", features = [
  "vendored",
  "lua54",
  "async",
  "send",
  "serialize",
] }
portable-pty = { version = "0.8.1" }
tauri = { version = "1.5.4", features = [ "window-maximize", "window-unminimize", "os-all", "window-unmaximize", "clipboard-all", "window-set-position", "window-set-size", "process-exit", "window-minimize", "window-start-dragging", "macos-private-api"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
window-vibrancy = { version = "0.4.3" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
