import { Config } from '../../types/config';

export const DEFAULT_CONFIG: Config = {
  acrylic: true,
  scrollback: 10000,
  copy_on_select: true,
  cursor_blink: true,
  cursor_style: 'bar',
  cursor_width: 1,
  font_size: 16,
  font_family: 'Consolas, Menlo, monospace',
  font_weight: 400,
  font_weight_bold: 700,
  letter_spacing: 1.0,
  line_height: 1.0,
  terminal_content_padding: {
    top: 8,
    bottom: 8,
    left: 8,
    right: 8,
  },
  terminal_border_width: 1,
  terminal_border_color_active: 'foreground',
  terminal_border_color_inactive: 'background',
  color_scheme: {
    cursor: '#56526e',
    cursor_accent: '#e0def4',
    selection_background: '#312f44',
    selection_foreground: '#e0def4',
    selection_inactive_background: '#312f44',
    background: '#232136',
    foreground: '#e0def4',
    black: '#393552',
    blue: '#9ccfd8',
    cyan: '#ea9a97',
    green: '#3e8fb0',
    magenta: '#c4a7e7',
    red: '#eb6f92',
    white: '#e0def4',
    yellow: '#f6c177',
    bright_black: '#817c9c',
    bright_blue: '#9ccfd8',
    bright_cyan: '#ea9a97',
    bright_green: '#3e8fb0',
    bright_magenta: '#c4a7e7',
    bright_red: '#eb6f92',
    bright_white: '#e0def4',
    bright_yellow: '#f6c177',
  },
  shells: [
    {
      name: 'Default',
      command: '',
      startup_directory: '',
    },
  ],
  default_shell_name: 'Default',
  keybind_leader: 'ctrl+b',
  keybinds: {
    create_tab: 'leader c',
    close_tab: 'leader shift+&',
    next_tab: 'leader n',
    previous_tab: 'leader p',
    tab1: 'leader 1',
    tab2: 'leader 2',
    tab3: 'leader 3',
    tab4: 'leader 4',
    tab5: 'leader 5',
    tab6: 'leader 6',
    tab7: 'leader 7',
    tab8: 'leader 8',
    tab9: 'leader 9',
    split_horizontal: 'leader shift+%',
    split_vertical: 'leader shift+"',
    focus_pane_left: 'leader h',
    focus_pane_right: 'leadedr l',
    focus_pane_up: 'leader k',
    focus_pane_down: 'leader j',
    close_pane: 'leader x',
  },
};
